name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2025
          - windows-11-arm
          - macos-26-intel
          - macos-26
        ref:
          - 5527a0292e62299031937ff8360329f5aa5cc6e6 # master
          - 715a528dff4785bd5f790aab31be38dff3634263 # mine
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: jurplel/install-qt-action
          ref: ${{ matrix.ref }}

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: action/

      - run: |
          pushd action
          npm ci || npm install
          npm run build
          popd
          sed -i.bak 's|uses: $/action|uses: ./action|' action.yml
          diff -u action.yml.bak action.yml || true
          git status --porcelain
        shell: bash

      - name: Install Qt 5.15.2 desktop
        if: ${{ startsWith(matrix.os, 'macos') }}
        id: qt-5_15_2-macos
        uses: ./
        with:
          version: '>=5.15,<6'
          target: desktop
          host: mac
          # aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7

      - name: Check Qt 5.15.2 desktop
        if: ${{ matrix.ref != '5527a0292e62299031937ff8360329f5aa5cc6e6' && startsWith(matrix.os, 'macos') }}
        env:
          OLD_QT_PATH: '${{ steps.qt-5_15_2-macos.outputs.qtPath }}'
          QT_VER:    ${{ steps.qt-5_15_2-macos.outputs.version }}
          QT_TARGET: ${{ steps.qt-5_15_2-macos.outputs.target  }}
          QT_ARCH:   ${{ steps.qt-5_15_2-macos.outputs.version }}
          QT_HOST:   ${{ steps.qt-5_15_2-macos.outputs.host    }}
          QT_PATH:   ${{ steps.qt-5_15_2-macos.outputs.qt-path }}
        shell: bash
        run: |
          set -u
  
          echo "Qt $QT_VER ($QT_TARGET/$QT_ARCH on $QT_HOST) \
          has been successfully installed in '$QT_PATH'."
  
          ls -l "$QT_PATH"

          printenv | sort

      - name: Install Qt 5.15.2 desktop
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        id: qt-5_15_2-linux
        uses: ./
        with:
          version: '>=5.15,<6'
          target: desktop
          host: linux
          # aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7

      - name: Check Qt 5.15.2 desktop
        if: ${{ matrix.ref != '5527a0292e62299031937ff8360329f5aa5cc6e6' && startsWith(matrix.os, 'ubuntu') }}
        env:
          OLD_QT_PATH: '${{ steps.qt-5_15_2-linux.outputs.qtPath }}'
          QT_VER:    ${{ steps.qt-5_15_2-linux.outputs.version }}
          QT_TARGET: ${{ steps.qt-5_15_2-linux.outputs.target  }}
          QT_ARCH:   ${{ steps.qt-5_15_2-linux.outputs.version }}
          QT_HOST:   ${{ steps.qt-5_15_2-linux.outputs.host    }}
          QT_PATH:   ${{ steps.qt-5_15_2-linux.outputs.qt-path }}
        shell: bash
        run: |
          set -u
  
          echo "Qt $QT_VER ($QT_TARGET/$QT_ARCH on $QT_HOST) \
          has been successfully installed in '$QT_PATH'."
  
          ls -l "$QT_PATH"

          printenv | sort

      - name: Install Qt 5.15.2 desktop
        if: ${{ startsWith(matrix.os, 'windows') }}
        id: qt-5_15_2-windows
        uses: ./
        with:
          version: '>=5.15,<6'
          target: desktop
          host: windows
          # aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7

      - name: Check Qt 5.15.2 desktop
        if: ${{ matrix.ref != '5527a0292e62299031937ff8360329f5aa5cc6e6' && startsWith(matrix.os, 'windows') }}
        env:
          OLD_QT_PATH: '${{ steps.qt-5_15_2-windows.outputs.qtPath }}'
          QT_VER:    ${{ steps.qt-5_15_2-windows.outputs.version }}
          QT_TARGET: ${{ steps.qt-5_15_2-windows.outputs.target  }}
          QT_ARCH:   ${{ steps.qt-5_15_2-windows.outputs.version }}
          QT_HOST:   ${{ steps.qt-5_15_2-windows.outputs.host    }}
          QT_PATH:   ${{ steps.qt-5_15_2-windows.outputs.qt-path }}
        shell: bash
        run: |
          set -u
  
          echo "Qt $QT_VER ($QT_TARGET/$QT_ARCH on $QT_HOST) \
          has been successfully installed in '$QT_PATH'."
  
          ls -l "$QT_PATH"

          printenv | sort

      - name: Install Qt 6.8.0 android
        id: qt-6_8_0
        uses: ./
        with:
          version: '>6.7,<6.8.1'
          target: android
          # aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7

      - name: Check Qt 6.8.0 android
        if: ${{ matrix.ref != '5527a0292e62299031937ff8360329f5aa5cc6e6' }}
        env:
          OLD_QT_PATH: '${{ steps.qt-6_8_0.outputs.qtPath }}'
          QT_VER:    ${{ steps.qt-6_8_0.outputs.version }}
          QT_TARGET: ${{ steps.qt-6_8_0.outputs.target  }}
          QT_ARCH:   ${{ steps.qt-6_8_0.outputs.arch    }}
          QT_HOST:   ${{ steps.qt-6_8_0.outputs.host    }}
          QT_PATH:   ${{ steps.qt-6_8_0.outputs.qt-path }}
        shell: bash
        run: |
          set -u
  
          echo "Qt $QT_VER ($QT_TARGET/$QT_ARCH on $QT_HOST) \
          has been successfully installed in '$QT_PATH'."
  
          ls -l "$QT_PATH"

          printenv | sort

      - name: Install Qt 6.8.1 android
        id: qt-6_8_1
        uses: ./
        with:
          version: '<6.8.2'
          target: android
          # aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7

      - name: Check Qt 6.8.1 android
        if: ${{ matrix.ref != '5527a0292e62299031937ff8360329f5aa5cc6e6' }}
        env:
          OLD_QT_PATH: '${{ steps.qt-6_8_1.outputs.qtPath }}'
          QT_VER:    ${{ steps.qt-6_8_1.outputs.version }}
          QT_TARGET: ${{ steps.qt-6_8_1.outputs.target  }}
          QT_ARCH:   ${{ steps.qt-6_8_1.outputs.arch    }}
          QT_HOST:   ${{ steps.qt-6_8_1.outputs.host    }}
          QT_PATH:   ${{ steps.qt-6_8_1.outputs.qt-path }}
        shell: bash
        run: |
          set -u
  
          echo "Qt $QT_VER ($QT_TARGET/$QT_ARCH on $QT_HOST) \
          has been successfully installed in '$QT_PATH'."
  
          ls -l "$QT_PATH"

          printenv | sort

      - name: Install Qt 6.8.3 desktop
        id: qt-6_8_3
        uses: ./
        with:
          version: '<6.9'
          target: desktop
          # aqtsource: git+https://github.com/miurahr/aqtinstall.git@076e1659807d0b362a3ed684d54c2e9c775eb9c7

      - name: Check Qt 6.8.3 desktop
        if: ${{ matrix.ref != '5527a0292e62299031937ff8360329f5aa5cc6e6' }}
        env:
          OLD_QT_PATH: '${{ steps.qt-6_8_3.outputs.qtPath }}'
          QT_VER:    ${{ steps.qt-6_8_3.outputs.version }}
          QT_TARGET: ${{ steps.qt-6_8_3.outputs.target  }}
          QT_ARCH:   ${{ steps.qt-6_8_3.outputs.arch    }}
          QT_HOST:   ${{ steps.qt-6_8_3.outputs.host    }}
          QT_PATH:   ${{ steps.qt-6_8_3.outputs.qt-path }}
        shell: bash
        run: |
          set -u
  
          echo "Qt $QT_VER ($QT_TARGET/$QT_ARCH on $QT_HOST) \
          has been successfully installed in '$QT_PATH'."
  
          ls -l "$QT_PATH"

          printenv | sort

      - name: Inspect all
        if: always()
        run: |
          find ../Qt
        shell: bash
